 -*- coding: utf-8 -*-
* Atlassian SDK workshop

** Innledning

Det vi skal gjøre idag er å lage en [[https://developer.atlassian.com/display/JIRADEV/Differences+between+Plugins1+and+Plugins2#DifferencesbetweenPlugins1andPlugins2-Plugins2][Atlassian type 2 plugin]] som inneholder en [[https://confluence.atlassian.com/display/DOC/Working+with+Macros][Confluence macro]] som henter litt data fra en [[https://confluence.atlassian.com/display/JIRA/What+is+an+Issue][Jira-sak]] og viser fram i en Confluence-side.

Tanken er å vise fram alt det man trenger å gjøre, men hoppe over det unødvendige og spare dere tid man fort kan bruke på blindspor og det å lete fram dokumentasjon (som det kan være lite av, det /er/ en del dokumentasjon på Atlassians sider, men man vet ikke nødvendigvis hva som er riktig og hva som er egentlig er avlegs før man har prøvd det).

*** Hva er en Confluence-makro
En Confluence-makro er et objekt man setter inn i sideeditoren til Confluence, og som genererer et XHTML-fragment når siden vises.

Vår makro skal kontakte en Jira-installasjon og hente beskrivelses-feltet fra en Jira-sak og formatere beskrivelsen som XHTML.

*** Litt om Atlassian-plugins

En Atlassian type 2-plugin kjøres som en OSGi-bundle i en OSGi runtime, og bruker Spring dependency injection for å få tak i APIet til applikasjonen den kjører i.

Man trenger ikke å vite noe om OSGi og plugin'en som den bygges er ikke en OSGi-bundle, men når man laster jar-fila opp i f.eks. Confluence, så vil den bli gjort om til en bundle før den lastes opp.

** Plan for dagen
Planen er at jeg gjør steg for steg i dette dokumentet som en live demo og så får dere prøve å gjøre de samme bitene.

Tingene vi skal gjøre:
 1. [[#laste-ned-og-installere-atlassian-sdk][Få alle opp og kjøre med utviklingsomgivelsen]]
 2. [[#starte-opp-jira-standalone][Starte en Jira fra SDKen]], [[#logge-inn-og-lag-eksempelprosjekt-og-en-sak-i-prosjektet][lage et prosjekt og en sak i Jiraen]]
 3. [[#lag-en-confluence-plugin][Lage en Confluence-plugin]]
 4. [[#sett-opp-ideen-p%C3%A5-pluginen][Importere Confluence-plugin'en som et Eclipse-prosjekt]]
 5. [[#starte-med-atlas-debug][starte en Confluence med plugin'en i]] (startes med mvn)
 6. [[#lag-en-makro-i-pluginen][Lage en makro i plugin'en]]
 7. [[#legg-p%C3%A5-issue-key-som-en-parameter-til-makroen][Legge på en parameter i makroen]] (en konfig-parameter man kan justere i side-editoren)
 8. [[#debug-inn-i-pluginen][Demonstrere debugging in i makroen]] (vi kan debugge koden mens den kjører inne i Confluence)
 9. [[#rapportere-feil-fra-makroen][Implementere feilrapportering i makroen]]
 10. [[#koble-makroen-mot-jira][Koble makroen mot Jira og hente data som vises fram]]

Og da er vi egentlig ferdige.  Dersom vi blir tidlig ferdige så kan vi prøve oss på å ta en annen plugin-modul, f.eks. et REST-endpoint.

** Laste ned og installere Atlassian SDK
   :PROPERTIES:
   :CUSTOM_ID: laste-ned-og-installere-atlassian-sdk
   :END:
 - Se [[https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project/install-the-atlassian-sdk-on-a-windows-system][Install the Atlassian SDK on a Windows System]]
 - Oppsett av eclipse
   - Installer eclipse
   - Installér m2e
 - Oppsett av IntelliJ
   - /TBD/

** Starte opp Jira standalone
   :PROPERTIES:
   :CUSTOM_ID: starte-opp-jira-standalone
   :END:
 - Åpne et cmd.exe og gi følgende kommandoer:
   : cd %USERPROFILE%
   : rmdir /s /q %USERPROFILE%\amps-standalone\target
   : atlas-run-standalone --product jira
   - /Merk:/ =rmdir=-kommandoen over sletter en eksisterende standalone-Jira, så om man allerede har en sånn instans man vil ta vare på, så /ikke/ kjør kommandoen
   - Når en tekst som dette vises i cmd.exe-vinduet, gå til [[Logge inn og lag eksempelprosjekt og en sak i prosjektet][neste steg]]:
     #+BEGIN_EXAMPLE
       ...
       [INFO] [talledLocalContainer] Tomcat 7.x started on port [2990]
       [INFO] jira started successfully in 301s at http://NOLSBANG02:2990/jira
       [INFO] Type Ctrl-D to shutdown gracefully
       [INFO] Type Ctrl-C to exit
     #+END_EXAMPLE
** Logge inn og lag eksempelprosjekt og en sak i prosjektet
   :PROPERTIES:
   :CUSTOM_ID: logge-inn-og-lag-eksempelprosjekt-og-en-sak-i-prosjektet
   :END:
 - Åpne [[http://localhost:2990/jira]] i en fane på en nettleser
 - Som "Username", skriv
   : admin
   som passord, skriv
   : admin
   Kryss av for "Remember my login on this computer"
 - Dersom Jira sier at URLen ikke matcher, klikk på banneret øverst for å endre navnet (klikk på "Update JIRA's base URL")
 - Åpne fra toppmenyen Projects->Create Project
 - I dialogen "Select Project Type":
   - Velg "Simple Issue Tracking" som prosjekttype
   - Klikk på knappen "Next"
   - Klikk på knappen "Select"
   - I "Name", skriv inn:
     : Eksempelprosjektet
   - Klikk på knappen "Submit"
 - Klikk på knappen "Create issue" (til høyre under "Get your project started")
 - I dialogen "Create Issue":
   - I feltet "Summary", skriv:
     : Vi må kunne vise issue-beskrivelser i Confluence
   - I feltet "Description" (litt nede i dialogen), skriv:
     : Når du kan lese denne teksten i Confluence er vi ferdige! Gratulerer!
   - Klikk på knappen "Create"
** Lag en confluence-plugin
   :PROPERTIES:
   :CUSTOM_ID: lag-en-confluence-plugin
   :END:
 - Start cmd.exe
 - cd til egnet sted, f.eks.
   : mkdir %USERPROFILE%\fagdag
   : cd %USERPROFILE%\fagdag
 : atlas-create-confluence-plugin --group-id no.steria.confluence --artifact-id sdkintro --version 1.0 --package no.steria.jira.confluence.plugins.sdkintro --non-interactive
 - /Merk:/ Alle fire argumenter (gruppe, artifact, versjon og pakke) må være på plass for at =--non-interactive= skal fungere
** Sett opp IDEen på plugin'en
   :PROPERTIES:
   :CUSTOM_ID: sett-opp-ideen-p%C3%A5-pluginen
   :END:

En del typer av plugin-moduler kan genereres med =atlas-create-confluence-plugin-module= men macro er ikke en av disse. Macro-moduler må lages manuelt.

*** Åpne Confluence-plugin'en i eclipse
 - Åpne eclipse på et nytt workspace:
   - I Dialogen "Workspace Launcher":
     - Klikk på knappen "Browse"
     - I dialogen "Select Workspace Directory":
       - I "Folder", skriv
         : %USERPROFILE%\fagdag
       - Klikk på knappen "OK"
     - Klikk på knappen "OK"
 - Legg til Atlassian SDK i i m2e:
   - Velg Window->Preferences
   - I "Preferences"-dialogen:
     - Velg Maven->Installations
     - Klikk på "Add..."
     - "Maven Installation"-dialogen:
       - Legg inn i Folder-feltet:
         : %USERPROFILE%\atlassian-plugin-sdk\apache-maven-3.2.1
       - Klikk på knappen "OK"
     - Klikk på knappen "OK"
 - Importer prosjektet i eclipse
   - Høyreklikk "Package Explorer" og velg: Import...
   - I dialogen "Import"
   - Velg Maven->Existing maven project
   - Klikk på knappen "Next>"
   - Klikk på knappen "Browse..."
   - I dialogen "Select Root Folder"
     - Velg mappen "fagdag"
     - Klikk på knappen "OK"
   - Klikk på knappen "Next>"
   - Klikk på knappen "Finish"
   - I dialogen "Incomplete Maven Goal Execution"
     - Klikk på knappen "OK"
       - (Byggefeilene tar vi i neste steg)
 - Fiks byggefeil i eclipse:
   - Høyreklikk første feil og velg: Quick Fix
   - I "Quick fix"-dialogen:
     - I "Select av fix", velg: Permanently mark goal compress-resources in pom.xml as ignored in eclipse build
     - Klikk på knappen "Finish"
     - I dialogen "Ignore"
       - Klikk på knappen "OK"
   - Høyreklikk første feil og velg: Quick Fix
   - I "Quick fix"-dialogen:
     - I "Select av fix", velg: Permanently mark goal compress-resources in pom.xml as ignored in eclipse build
     - I "Problems" klikk på knappen "Select All"
     - Klikk på knappen "Finish"
     - I dialogen "Ignore"
       - Klikk på knappen "OK"
   - Høyreklikk prosjektet "sdkintro" i "Package Explorer" og velg: Maven->Update Project...
   - I dialogen "Update Maven Project"
     - Klikk på knappen "OK"
*** Åpne Confluence-plugin'en i IntelliJ
** Starte med atlas-debug
   :PROPERTIES:
   :CUSTOM_ID: starte-med-atlas-debug
   :END:
 - Først start et cmd.exe og ta:
   : cd %USERPROFILE%\fagdag\sdkintro
   : atlas-debug
 - Vent til det kommer en utskrift ala dette:
   : [INFO] confluence started successfully in 220s at http://NOLSBANG02:1990/confluence
   : [INFO] Type Ctrl-D to shutdown gracefully
   : [INFO] Type Ctrl-C to exit
 - Åpne en nettleserfane på [[http://localhost:1990/confluence]]
   - Logg inn med brukernavn
     : admin
     og passord
     : admin
     Kryss av for "Remember me"
 - Lag en side
   - Klikk på knappen "Create" (øverst på sida, litt til venstre for midten)
   - I dialogen "Create":
     - Velg "Blank page"
     - Klikk på knappen "Create"
   - I tittelfeltet (der det står "New page") gi en tittel. f.eks.:
     : Min testside
   - Velg: +Insert->Other Macros
   - I dialogen "Select Macro":
     - I tekstboksen oppe til høyre (til venstre for hyperlenken "Help"), skriv inn:
       : hello
     - Observer at man ikke får noen treff
     - Klikk på "Cancel"
   - Klikk på knappen "Save"
** Lag en makro i plugin'en
   :PROPERTIES:
   :CUSTOM_ID: lag-en-makro-i-pluginen
   :END:
*** I eclipse
 - Åpne eclipse på [[Åpne Confluence-plugin'en i eclipse][workspace't der man importerte plugin-prosjektet]]
 - Lag en ny pakke:
   - Åpne mappen =src/main/java=
   - Høyreklikk pakken som allerede ligger der og ta: New->Package
   - I dialogen "New Java Package":
     - I "Name", legg inn:
       : no.steria.jira.confluence.plugins.sdkintro.macros
     - Klikk på knappen "Finish"
 - Lag en makro i pakken =no.steria.jira.confluence.plugins.sdkintro.macro=
   - Lag en ny klasse som implementerer interface't [[https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/macro/Macro.html][Macro]]:
     - Høyreklikk =no.steria.jira.confluence.plugins.sdkintro.macro= og ta New->Class
     - I dialogen "New Java Class":
       - I "Name", skriv:
         : HelloJiraIssueMacro
       - Klikk på knappen "Add..." ved "Interfaces"
       - I dialogen "Implemented Interfaces Selection":
         - I "Choose interfaces", skriv:
           : macro
         - I "Matching items", velg:
           : Macro - com.atlassian.confluence.macro
           (antagelig førstevalget)
         - Klikk på knappen "OK"
       - Klikk på knappen "Finish"
   - Følgende kode blir generert:
     #+BEGIN_SRC java
       package no.steria.jira.confluence.plugins.sdkintro.macro;

       import java.util.Map;

       import com.atlassian.confluence.content.render.xhtml.ConversionContext;
       import com.atlassian.confluence.macro.Macro;
       import com.atlassian.confluence.macro.MacroExecutionException;

       public class HelloJiraIssueMacro implements Macro {

               @Override
               public String execute(Map<String, String> arg0, String arg1,
                               ConversionContext arg2) throws MacroExecutionException {
                       // TODO Auto-generated method stub
                       return null;
               }

               @Override
               public BodyType getBodyType() {
                       // TODO Auto-generated method stub
                       return null;
               }

               @Override
               public OutputType getOutputType() {
                       // TODO Auto-generated method stub
                       return null;
               }

       }
     #+END_SRC
   - Fiks =execute()=, argumentene (sånn at de blir de samme som i [[https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/macro/Macro.html#execute(java.util.Map, java.lang.String, com.atlassian.confluence.content.render.xhtml.ConversionContext)][Macro.execute()]])
     #+BEGIN_SRC java
       @Override
       public String execute(Map<String, String> parameters, String body, ConversionContext context) throws MacroExecutionException {
               // TODO Auto-generated method stub
               return null;
       }
     #+END_SRC
   - Fyll inn innhold i metodene:
     #+BEGIN_SRC java
       @Override
       public String execute(Map<String, String> parameters, String body, ConversionContext context) throws MacroExecutionException {
               return "<b>HelloJiraIssue macro is here!</b>";
       }

       @Override
       public BodyType getBodyType() {
               return BodyType.NONE;
       }

       @Override
       public OutputType getOutputType() {
               return OutputType.BLOCK;
       }
     #+END_SRC
 - Legg inn klassen i plugin-konfigurasjonen:
   - Åpne mappen =src/main/resources=
   - Åpne fila =atlassian-plugin.xml=
   - Legg inn følgende XML-kode i =atlassian-plugin.xml= (nivået under topp-elementet =<atlassian-plugin>=, rett etter =<web-resource>=)
     #+BEGIN_SRC nxml
       <xhtml-macro name="hello-jira-issue-macro" class="no.steria.jira.confluence.plugins.sdkintro.macros.HelloJiraIssueMacro" key="hello-jira-issue-macro">
           <parameters/>
       </xhtml-macro>
     #+END_SRC
 - Start et nytt cmd.exe og ta:
   : cd %USERPROFILE%\fagdag\sdkintro
   : atlas-cli
 - Når det kommer en prompt =maven>= så gi følgende kommando (fulgt av RET):
   : pi
 - Sjekk at makroen er på plass:
   - Gå til Confluence i en nettleser ([[http://localhost:1990/confluence]]) og ta Edit på sida du lagde tidligere ("Min testside")
   - Velg: +Insert->Other Macros
   - I dialogen "Select Macro":
     - I tekstboksen oppe til høyre (til venstre for hyperlenken "Help"), skriv inn:
       : hello
     - Observer at makroen "Hello jira issue" dukker opp, og velg denne
     - Klikk på knappen "Insert"
   - Klikk på knappen "Save" (nederst i side-editoren)
 - Siden har nå teksten "*HelloJiraIssue macro is here!*"
*** I IntelliJ
 - /TBD/
** Legg på "issue key" som en parameter til makroen
   :PROPERTIES:
   :CUSTOM_ID: legg-p%C3%A5-issue-key-som-en-parameter-til-makroen
   :END:
 - Sjekk at makroen ikke har noen parameter:
   - Gå til Confluence i en nettleser ([[http://localhost:1990/confluence]]) og ta Edit på sida du lagde tidligere ("Min testside")
     - Klikk på "Edit" (oppe til høyre på siden, samme rad som "Tools"
     - Klikk på "Hello jira issue macro" og velg "Edit"
     - "Preview" viser teksten "HelloJiraIssue macro is here"
     - Ingen parametere vises
   - Klikk på "Cancel" (nederst i side-editoren)
 - Legg inn parameteren i plugin-konfigurasjonen:
   - Åpne mappen =src/main/resources=
   - Åpne fila =atlassian-plugin.xml=
   - Endre <xhtml-macro>-elementet i =atlassian-plugin.xml= slik:
     #+BEGIN_SRC nxml
       <xhtml-macro name="hello-jira-issue-macro" class="no.steria.jira.confluence.plugins.sdkintro.macros.HelloJiraIssueMacro" key="my-macro">
        <parameters>
         <parameter name="jiraIssueKey" type="string"/>
        </parameters>
       </xhtml-macro>
     #+END_SRC
 - I cmd.exe som kjører =atlas-cli=, gi kommandoen:
   : pi
 - Gå tilbake til fanen åpen mot Confluence ([[http://localhost:1990/confluence]]) og sjekk makroen nå har en parameter:
   - Gå til "Min testside" åpen i side-editoren
   - Klikk på "Hello jira issue macro" og velg "Edit"
   - Makroen har nå en parameter jiraIssueKey
 - Endre =execute()=-metoden til HelloJiraIssueMacro, til at den blir slik:
   #+BEGIN_SRC java
     @Override
     public String execute(Map<String, String> parameters, String body, ConversionContext context) throws MacroExecutionException {
             String jiraIssueKey = parameters.get("jiraIssueKey");
             return "<b>HelloJiraIssue macro for issue: " + jiraIssueKey + "</b>";
     }
   #+END_SRC
 - I cmd.exe som kjører =atlas-cli=, gi kommandoen:
   : pi
 - Ta en reload på "Min testside" og observer at teksten i fet skrift er "Hello jira issue macro for:(null)"
** Debug inn i plugin'en
   :PROPERTIES:
   :CUSTOM_ID: debug-inn-i-pluginen
   :END:
Ettersom vi startet "atlas-debug" på plugin-prosjektet istedenfor "atlas-run" så har vi en mulighet til å debugge direkte inn i plugin'en.
*** Med eclipse
 - Velg fra menyen Run->Debug Configurations...
 - I dialogen "Debug Configurations":
   - Velg "Remote Java Appliation"
   - Klikk på "new"-knappen (Et stående rektangel med gult plusstegn oppe til høyre)
   - I "Name", skriv:
     : sdkintro confluence
   - Klikk på knappen "Browse..." ved "Project"
   - I dialogen "Project Selection":
     - Velg prosjektet "sdkintro" (eneste prosjekt her)
     - Klikk på knappen "OK"
   - Under "Connection Properties":
     - For "Host", skriv:
       : localhost
     - For "Port", skriv:
       : 5005
   - Klikk på knappen "Debug"
 - I =HelloJiraIssueMacro.java=:
   - Sett breakpoint på første linje i =execute()=-metoden:
     #+BEGIN_SRC java
       String jiraIssueKey = parameters.get("jiraIssueKey");
     #+END_SRC
 - Ta en reload på "Min testside" i nettleseren
 - Godta bytte til "Debug perspective"
 - Debuggeren i eclipse stopper på første linje
 - Se på variable step litt og ta continue
 - I "Debug"-fanen:
   - Høyreklikk "sdkintro confluence" og velg Disconnect
 - Gå tilbake til Java perspective
*** Med IntelliJ
** Rapportere feil fra makroen
   :PROPERTIES:
   :CUSTOM_ID: rapportere-feil-fra-makroen
   :END:
Ved å kaste en [[https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/macro/MacroExecutionException.html][MacroExecutionException]] kan man både rapportere feil der makroen står på en Confluence-side og i loggen til Confluence.

 - Endre =execute()= i =HelloJiraIssueMacro til dette:
   #+BEGIN_SRC java
     @Override
     public String execute(Map<String, String> parameters, String body, ConversionContext context) throws MacroExecutionException {
             String jiraIssueKey = parameters.get("jiraIssueKey");
             if (null == jiraIssueKey) {
                     throw new MacroExecutionException("A jiraIssueKey referencing a valid Jira issue is required");
             }
             return "<b>HelloJiraIssue macro for:" + jiraIssueKey +"</b>";
     }
   #+END_SRC
 - Gå til cmd.exe som kjører =atlas-cli= og gi kommandoen:
   : pi
 - Ta en reload på "Min testside" og se at instedenfor "Hello jira issue macro for:(null)", står det nå "Error rendering macro 'hello-jira-issue-macro' : A jiraIssueKey referencing a valid Jira issue is required"
 - Klikk på "Edit" (oppe til høyre på "Min testside")
 - Klikk på "Hello jira issue macro" (grå boks) og velg "Edit"
 - I dialogen "Edit 'Hello jira issue macro' Macro":
   - I "jiraIssueKey", skriv:
     : EK-1
   - Klikk på knappen "Save"
 - Klikk på "Save" (nederst på sida i sideeditoren)
 - Siden vil nå vise teksten "*HelloJiraIssue macro for:EK-1*"
 - Gå til cmd.exe som kjører =atlas-debug= og se at man finner en slik linje (SDK Confluence logger til konsoll istedenfor til f.eks. catalina.out):
   : [INFO] [talledLocalContainer] 2015-01-14 12:49:10,731 WARN [http-1990-7] [xhtml.view.macro.ViewMacroMarshaller] marshalInternal Exception executing macro: hello-jira-issue-macro, with message: A jiraIssueKey referencing a valid Jira issue is required
   - SDK Jira logger til en fil
** Koble makroen mot Jira
   :PROPERTIES:
   :CUSTOM_ID: koble-makroen-mot-jira
   :END:
 - Vi skal bruke [[https://docs.atlassian.com/jira/REST/latest/#d2e4292][Jira REST API]]
 - Få inn en [[https://docs.atlassian.com/applinks-api/3.2/com/atlassian/applinks/api/EntityLinkService.html][EntityLinkService]] og bruke denne til å navigere til koblet Jira:
   - Legg til =org.json:json= som "provided" avhenghet, dvs.:
     #+BEGIN_SRC nxml
       <dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>20141113</version>
        <scope>provided</scope>
       </dependency>
     #+END_SRC
     - I Eclipse:
       - Åpne =pom.xml= i sdkintro-prosjeket
       - Velg fanen "Dependencies"
       - Klikk på knappen "Add..."
       - I dialogen "Select Dependency"
         - I "Enter groupId, artifactId or sha1 prefi or pattern(*)", skriv:
           : org.json
         - I "Search results":
           - velg "org.json json"
             - Mulig at du må scrolle nedover for å finne den
         - I "Scope", velg "provided"
         - Klikk på knappen "OK"
       - Lagre =pom.xml=
     - I IntelliJ:
       - TBD!
   - Legg til =EntityLinkService= som en komponentavhengighet:
     - Åpne =src/main/resoures=-mappen
     - Åpne =atlassian-plugin.xml=
     - Legg inn følgende linje etter ekisterende <component-import>:
       #+BEGIN_SRC nxml
         <component-import key="entityLinkService" interface="com.atlassian.applinks.api.EntityLinkService" />
       #+END_SRC
   - Lag en konstruktør (og to felt) i HelloJiraIssueMacro, som ser sånn ut:
     #+BEGIN_SRC java
       private SpaceManager spaceManager;
       private EntityLinkService entityLinkService;

       public HelloJiraIssueMacro(SpaceManager spaceManager, EntityLinkService entityLinkService) {
               this.entityLinkService = entityLinkService;
               this.spaceManager = spaceManager;
       }
     #+END_SRC
     Det vi gjør her, er å få [[https://developer.atlassian.com/display/CONFDEV/Accessing+Confluence+Components+from+Plugin+Modules#AccessingConfluenceComponentsfromPluginModules-Constructor-basedinjection(v2plugins)][Spring dependency injection]] av [[https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/spaces/SpaceManager.html][SpaceManager]] og [[https://docs.atlassian.com/applinks-api/3.2/com/atlassian/applinks/api/EntityLinkService.html][EntityLinkService]]
     
     SpaceManager-objektet skal vi bruke til å finne et [[https://docs.atlassian.com/confluence/latest/com/atlassian/confluence/spaces/Space.html][Space]]
     EntityLinkService-objektet skal vi så bruke til å få kontakt med et Jira-prosjekt som er koblet mot prosjektet, og derfra en Jira-instans.
   - Endre =execute()=-metoden til å se slik ut:
     #+BEGIN_SRC java
       @Override
       public String execute(Map<String, String> parameters, String body, ConversionContext context) throws MacroExecutionException {
               String jiraIssueKey = parameters.get("jiraIssueKey");
               if (null == jiraIssueKey) {
                       throw new MacroExecutionException("A jiraIssueKey referencing a valid Jira issue is required");
               }

               // Find the factory that creates requests
               Space currentSpaceForPageWithMacro = spaceManager.getSpace(context.getSpaceKey());
               EntityLink jiraProjectLink = entityLinkService.getPrimaryEntityLink(currentSpaceForPageWithMacro, JiraProjectEntityType.class);
               if (null == jiraProjectLink) {
                       throw new MacroExecutionException("No application link from the Confluence space \"" + currentSpaceForPageWithMacro.getName() + "\" to a Jira project!");
               }
               ApplicationLinkRequestFactory jiraRequestFactory = jiraProjectLink.getApplicationLink().createAuthenticatedRequestFactory();

               // Do a REST API call to fetch the data of the issue of the macro parameter
               String jiraIssueRESTEndpoint = "/rest/api/2/issue/" + jiraIssueKey;
               String jiraIssueJson = null;
               try {
                       ApplicationLinkRequest jiraIssueGetRequest = jiraRequestFactory.createRequest(MethodType.GET, jiraIssueRESTEndpoint);
                       jiraIssueJson = jiraIssueGetRequest.execute();
                       JSONObject jiraIssue = new JSONObject(jiraIssueJson);
                       JSONObject jiraIssueFields = jiraIssue.getJSONObject("fields");

                       String jiraIssueDescription = jiraIssueFields.getString("description");

                       return "<b>Description for issue " + jiraIssueKey + ":</b> " + jiraIssueDescription + "<br/>";
               } catch (CredentialsRequiredException e) {
                       // Re-throw as a MacroExecutionException, which is what Confluence expects.
                       throw new MacroExecutionException(e);
               } catch (ResponseException e) {
                       // Re-throw as a MacroExecutionException, which is what Confluence expects.
                       throw new MacroExecutionException(e);
               } catch (JSONException e) {
                       String msg = "Problems parsing response as JSON: " + e.getMessage() + "  received JSON: " + jiraIssueJson;
                       throw new MacroExecutionException(msg);
               }
       }
     #+END_SRC
 - Gå til cmd.exe som kjører =atlas-cli= og gi kommandoen:
   : pi
 - Ta en reload på "Min testside" og se at teksten endrer seg fra 
   : Error rendering macro 'hello-jira-issue-macro' : A jiraIssueKey referencing a valid Jira issue is required
   til
   : Error rendering macro 'hello-jira-issue-macro' : No application link from the Confluence space "Demonstration Space" to a Jira project!
 - Så da må vi først koble sammen Confluence og Jira
   - I Confluence, åpne tannhjulsmenyen oppe til høyre og velg "General Configuration"
   - I siden som åpnes i nettleseren, skroll nederst på sida og velg "Application Links" fra lista i venstre kant (under "ADMINISTRATION")
   - I boksen med teksten "Enter the URL of the application you want to link", skriv:
     : http://localhost:2990/jira
   - Klikk på knappen "Create new link"
   - I dialogen "Link applications"
     - Kryss av "The server have the same set of users and usernames"
     - Klikk på knappen "Continue"
     - Klikk på knappen "Continue" en gang til
   - Klikk på "Edit" helt til høyre på linja som starter med "Your Company JIRA"
   - I dialogen "Configure Your Company JIRA":
     - Velg "Outgoing Authentication"
     - Velg fanen "Trusted Applications", skroll ned til bunnen og klikk på knappen "Enable"
     - Velg "Incoming Authentication"
     - Velg fanen "Trusted Applications", skroll ned til bunnen og klikk på knappen "Enable"
       - Dersom det kommer en feilmelding, bare klikk på URLen som vises
     - Klikk på "Close"
 - Når Confluence og Jira er koblet sammen, så må vi koble sammen Confluence-space't med et Jira-prosjekt
   - Velg fra menyen på toppen: Spaces->Demonstration Space
   - Velg "Space.tools->Integrations" fra dropdownmenyen nederst til venstre
   - Åpne "+ Add Link" (til høyre på siden), velg: Your Company JIRA (JIRA)
   - I dialogen "Enter link details":
     - Klikk på knappen "Create"
   - Klikk på "Pages" (oppe til venstre på siden)
   - Velg "Min testside", denne bør nå inneholde teksten "*Description for issue EK-1*: Når du kan lese denne teksten i Confluence er vi ferdige! Gratulerer!"

